# Generated by Django 3.2.6 on 2021-08-05 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=220, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sponsor_name', models.CharField(max_length=120)),
                ('sponsor_logo', models.FileField(null=True, upload_to='logos/sponsor_logo/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/{self.title}/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('redeem_status', models.IntegerField(choices=[(0, 'Not Redeemed'), (1, 'Redeemed')], default=0)),
                ('location', models.ManyToManyField(blank=True, to='product.Location')),
            ],
            options={
                'ordering': ['title', 'sponsor_name'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_number', models.IntegerField()),
                ('coupon_image', models.ImageField(null=True, upload_to='coupons/%Y/%m/%d/')),
                ('qrcode_string', models.CharField(max_length=250, null=True)),
                ('sms_number', models.IntegerField(blank=True, null=True)),
                ('keyword', models.CharField(max_length=12, null=True)),
                ('terms_n_conditions', models.CharField(max_length=560, null=True)),
                ('offer_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_redemption', to='product.offer')),
            ],
            options={
                'ordering': ['offer_title'],
            },
        ),
    ]
